# Generated by Django 4.2.4 on 2023-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='charisma',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='constitution',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='dexterity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='hit_points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='intelligence',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='strength',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='wisdom',
            field=models.IntegerField(blank=True),
        ),
    ]
