# Generated by Django 4.2.4 on 2023-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_alter_heroes_charisma_alter_heroes_constitution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
