# Generated by Django 4.2.4 on 2023-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_heroes_charisma_alter_heroes_constitution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bonuses', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bonuses', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
