# Generated by Django 4.2.4 on 2023-09-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_heroes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='hero_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='heroes.heroclass'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='heroes.race'),
        ),
    ]
